# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
hostssl all             all             0.0.0.0/0               cert map=ssl_map
hostssl all             all             ::0/0                   cert map=ssl_map
